# fly.toml app configuration file generated for haunts-3 on 2023-06-02T12:12:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "haunts-3"
primary_region = "lhr"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
